create table if not exists mieterakte_oracle_snapshot (
    persvv_id bigint primary key,
    person_id bigint not null,
    name text,
    vorname text,
    email text,
    webpasswort text,
    wohnheim_id bigint,
    wohnheim_suchname text,
    wohnheim_name text,
    vo_id bigint,
    vo_suchname text,
    art integer,
    beginn date,
    ende date,
    perspersonenartid bigint,
    vertragsart_id bigint,
    status integer,
    statusname text,
    source_hash text,
    raw_json jsonb,
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    last_changed_at timestamptz
);

create table if not exists mieterakte_state (
    persvv_id bigint primary key references mieterakte_oracle_snapshot(persvv_id),
    person_id bigint not null,
    vo_id bigint,
    wohnheim_id bigint,
    person_path text,
    share_id text,
    share_link text,
    share_expiration_date date,
    folder_created_at timestamptz,
    templates_copied_at timestamptz,
    move_in_mail_sent_at timestamptz,
    move_out_mail_sent_at timestamptz,
    last_seen_at timestamptz not null default now(),
    last_processed_at timestamptz,
    last_status text,
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists mieterakte_run_log (
    run_id uuid primary key,
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    dry_run boolean not null,
    create_folders boolean not null,
    create_shares boolean not null,
    send_emails boolean not null,
    preview_emails boolean not null,
    use_postgres boolean not null,
    process_from_postgres boolean not null,
    oracle_records_read integer,
    records_processed integer,
    folders_created integer,
    folders_skipped_existing integer,
    shares_created integer,
    shares_updated integer,
    shares_skipped integer,
    mails_prepared_or_sent integer,
    mail_previews_created integer,
    template_files_copied integer,
    template_files_skipped integer,
    template_copy_errors integer,
    warnings integer,
    errors integer,
    result_json jsonb
);
